FROM python:3.8.13-slim

COPY ./ /root/code
RUN apt-get update && apt-get install gcc -y
RUN cd /root/code && python3 -m pip install --upgrade pip && pip install torch==1.11+cpu -f https://download.pytorch.org/whl/torch_stable.html && python3 -m pip install -e .[dev]

CMD /bin/bash