version: 1
loggers:
  '': # Root
    level: NOTSET
    handlers:
      - debug_console_handler
      - info_rotating_file_handler
  'agent':
    level: NOTSET
    handlers:
      - debug_console_handler
      - info_rotating_file_handler
handlers:
  debug_console_handler:
    level: DEBUG
    formatter: info
    class: logging.StreamHandler
    stream: 'ext://sys.stderr'
  info_rotating_file_handler:
    level: INFO
    formatter: info
    class: logging.handlers.RotatingFileHandler
    filename: yawning_titan.log
    maxBytes: 10485760 # 10MB
    backupCount: 10 # Max 100MB of logs
    encoding: utf8
formatters:
  info:
    format: '%(asctime)s::%(levelname)s::%(name)s::%(funcName)s::%(lineno)s::%(message)s'
